Adding sensors for some simple attributes measured by Kumo units
dlarrick/hass-kumo pull request #113
Opened 2023-05-30 22:09 UTC by barndawgie

I modeled the below on existing code you had for head unit wi-fi signal as I'm not much of a python dev. It seems to work but I'm very open to feedback.

I couldn't figure out an easy/good way to determine if there was a sensor and thus always create disabled entities for the Humidity, Sensor Battery, and Sensor RSSI sensors; is there some has_sensor() call I could be making and just didn't see in pykumo?

2023-05-30 22:11 UTC, barndawgie commented
I have tested these with my setup. I have a few PAC-USWHS003-TH-1 sensors rather than a MHK control unit.

2023-07-03 17:56 UTC, dlarrick commented
Sorry for the delay in replying here.

Communication with the indoor units is notoriously fickle, especially these days with the problems seen in #105 . So I would hate to base a decision about whether to create a sensor on our ability to properly query the indoor unit at startup. So I think your approach of creating them disabled and letting people enable if they like, is a good one. Another fancier approach would be to provide toggles in the setup, but IMHO that's more than is required.

A couple notes though:
- There are some typos / inconsistencies in the code & comments. I'll make individual notes in the PR.
- Please also update the README.md to mention these sensors and how to enable them.

2023-07-03 18:03 UTC, dlarrick requested changes
The only issues I see with the code are in comments (please update). Code itself looks good. As I noted, please also update README.md to document the sensors that get added, and which ones are disabled by default. I'm planning to push a new release this week, and if you can get me these changes I'll include it.

2023-07-03 18:03 UTC, dlarrick commented on custom_components/kumo/sensor.py
> +        _LOGGER.debug("Adding entity: sensor_wifi_signal for %s", coordinator.get_device().get_name())
The sensor doesn't use WiFi. I'm unclear if it's Bluetooth or something proprietary, but it runs for years on a (big) lithium coin cell, so I suspect the latter.
So it's definitely reporting a signal strength, but calling it WiFi is misleading.

2023-07-03 18:03 UTC, dlarrick commented on custom_components/kumo/sensor.py
> +    """Representation of a Kumo's WiFi Signal Strength."""
Comment doesn't match the class

2023-07-03 18:03 UTC, dlarrick commented on custom_components/kumo/sensor.py
> +    """Representation of a Kumo's WiFi Signal Strength."""
Comment doesn't match the class (and it's not Wifi, as noted elsewhere)

2023-07-03 18:03 UTC, dlarrick commented on custom_components/kumo/sensor.py
> +        """Disable entity by default."""
Misleading comment

2023-07-10 21:48 UTC, barndawgie commented
I believe I've addressed all of your requested changes. Thanks!

2023-07-11 01:11 UTC, dlarrick commented
Thanks, will review this week.

2023-08-06 14:49 UTC, dlarrick approved these changes

2023-08-06 14:49 UTC, merged