New IP address missing detection and prompt
dlarrick/hass-kumo pull request #57
Opened 2021-08-29 08:39 UTC by danielgoepp

Omriasta added the ability to detect missing IP addresses from the kumo cloud service, and prompt the user to enter their addresses. Also you can now edit them in the config after install.

2021-08-29 14:44 UTC, omriasta commented
@dlarrick I commented in the issue but just an FYI, I changed the code for prefer_cache so it is forced to True if the cache file is missing IP addresses. If someone setup the integration with this set as false, it would work only until home assistant was restarted at which point the cache would be loaded direct from kumo and wouldn't have ips again. Not sure if that is ok but maybe we should add that note to the form that shows up if ips are missing. Also, if you have a better idea of how we can set labels dynamically in that form so that it looks better rather than populating the unit names and Mac as the default entry, I'll be glad to take another go at it.

2021-09-06 15:29 UTC, dlarrick commented on custom_components/kumo/config_flow.py
> +                    for raw_unit in child["zoneTable"].values():
Also need to go through the "children" as in [pykumo](https://github.com/dlarrick/pykumo/blob/master/pykumo/pykumo.py#L537-L542) in order to handle units that are in changeover groups.

2021-09-06 15:31 UTC, dlarrick commented on custom_components/kumo/config_flow.py
> +    async def async_step_confirm(self, user_input=None):
maybe call this `async_step_request_ips` for clarity?

2021-09-06 15:31 UTC, dlarrick commented on custom_components/kumo/config_flow.py
> +                            raw_unit["address"] = user_input[x]
Also need to go thru the children here

2021-09-06 15:34 UTC, dlarrick commented on custom_components/kumo/config_flow.py
> +                )
...and here, and in the next loop. It may be worth a pair of utility functions to get / set the IPs for all the units

2021-09-06 15:35 UTC, omriasta commented
I guess I missed the "grandchildren" since my setup is so simple. I will try to look over these and correct bit will be pretty busy this week and then "off the grid" myself from Thursday. Maybe @danielgoepp  can try and correct these?

2021-09-06 15:36 UTC, dlarrick commented on custom_components/kumo/translations/en.json
> +        "description": "Kumo failed to return an IP for the following units, please replace the text with the local IP"
Please separate this into 2 sentences, not spliced together with a comma. Also, I'd suggest "failed to return an IP address" and "with their local IP addresses"

2021-09-06 15:37 UTC, dlarrick requested changes
This looks good, just need to handle the changeover groups. I also made a couple of cosmetic comments.

2021-09-06 15:57 UTC, dlarrick commented
> I guess I missed the "grandchildren" since my setup is so simple. I will try to look over these and correct but will be pretty busy this week and then "off the grid" myself from Thursday. Maybe @danielgoepp can try and correct these?

Oh no worries, this is easy to miss ... I missed it myself in the original implementation, as did the author of kumojs in their first node.js library. If Daniel doesn't get to it I might have some time myself late in the week. (though why does "a week off at home" turn into "here are 30 things to get done since you're not working this week"?)

Ideally all the parsing & editing of the raw JSON could move to pykumo so the integration can be insulated from those details. Something like "get_raw_indoor_units" that gets a dict of units (keyed by MAC or serial) from the raw JSON, and "override_indoor_unit_info" that accepts that same dict (with the user's input) and makes those changes in the raw JSON.

2021-09-07 08:34 UTC, danielgoepp commented
Thanks for all the updates. I'm unlikely to get to this during the week, but might be able to check it out this weekend. Also just an FYI I have a ticket open with Mitsubishi trying to get to the root cause of why the IP are not saving in the first place. It's been a little painful so far, as you might imagine ;) However, I have not given up hope yet.

2021-09-07 22:10 UTC, danielgoepp commented
@omriasta I have invited you to my repository which I forked from @dlarrick. If you prefer to update yours, if you want to give me access I'm happy to do the formatting updates directly there too. I don't think we need to do this bouncing back and fourth though ;)

2021-09-08 00:39 UTC, danielgoepp commented
I think that would be easier, if you are okay with it. I know I certainly would never touch master directly, always branch. I'm a fan of the git-flow method but don't necessarily need to add that complexity here. At a minimum I think just adding a develop branch and working off feature branches from there.

2021-09-08 11:54 UTC, omriasta commented
OK, I think I did it.....there is a new PR from a branch I created. Hopefully I didn't mess anything up....

2021-09-08 13:09 UTC, danielgoepp commented
Looks about right to me. I'll close this pull request then to avoid confusion.

2021-09-08 13:09 UTC, closed without merging